controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

common_controllers:
    resource:
        path: ../src/Controller/Common/
        namespace: App\Controller\Common
    type: attribute
