# config/services.yaml
<<<<<<< HEAD
=======
# config/services.yaml
>>>>>>> shop

parameters:
    # Always use environment variables for sensitive data
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
<<<<<<< HEAD
    images_directory: "%kernel.project_dir%/public/profile_images"

=======
>>>>>>> shop

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # Inject your Gemini API key into any constructor argument named $geminiApiKey
            string $geminiApiKey: '%env(GEMINI_API_KEY)%'

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Stripe Checkout controller with injected API keys
    App\Controller\Front\Shop\CheckoutController:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
            $stripePublicKey: '%stripe_public_key%'
        tags: ['controller.service_arguments']

    # Optional Stripe helper service
    App\Service\StripeService:
        arguments:
            $secretKey: '%stripe_secret_key%'

    # Authentication success handler
    App\Security\LoginSuccessHandler:
        tags:
            - { name: 'security.authentication.success_handler' }

    # Recommendation Bundle services
    App\RecommendationBundle\Service\RecommendationEngine: ~

    App\RecommendationBundle\Controller\RecommendationController:
        tags: ['controller.service_arguments']
