# config/services.yaml

parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    images_directory: "%kernel.project_dir%/public/profile_images"
    tips_api_base_url: '%env(resolve:TIPS_API_BASE_URL)%'
    events_directory: '%kernel.project_dir%/public/uploads/events'

services:
    _defaults:
        autowire: true      
        autoconfigure: true 
        bind:
            string $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\Front\Shop\CheckoutController:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'
            $stripePublicKey: '%stripe_public_key%'
        tags: ['controller.service_arguments']

    App\Service\StripeService:
        arguments:
            $secretKey: '%stripe_secret_key%'

    App\RecommendationBundle\Service\RecommendationEngine: ~

    App\RecommendationBundle\Controller\RecommendationController:
        tags: ['controller.service_arguments']
